### ISSUE TITLE
Error: json-read: JSON readtable error: 117

### ISSUE THREAD

**Issue by snowman** [knu/yaml-imenu.el#3]
#### Steps to reproduce

```yaml
# FILE /tmp/fruits.yaml
---
fruit:
  apple: '$ 1.00'
```

```sh
$ emacs -Q \
  --load /path/to/yaml-mode.el  \
  --load /path/to/yaml-imenu.el

M-x yaml-imenu-enable RET

C-x C-f /tmp/fruits.yaml RET

M-x imenu RET

  json-read: JSON readtable error: 117
```
